Resources:
  AccessRoleEC309AE6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    Metadata:
      aws:cdk:path: AppRunnerStack/AccessRole/Resource
  InstanceRole3CCE2F1D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: ssm:GetParameters
                Effect: Allow
                Resource: arn:aws:ssm:eu-central-1:495599779087:parameter/hands-on-aws/containers/api-key
            Version: "2012-10-17"
          PolicyName: SsmReadPolicy
    Metadata:
      aws:cdk:path: AppRunnerStack/InstanceRole/Resource
  AutoScaling:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: app-runner-autoscaling
      MaxConcurrency: 100
      MaxSize: 3
      MinSize: 1
    Metadata:
      aws:cdk:path: AppRunnerStack/AutoScaling
  Service:
    Type: AWS::AppRunner::Service
    Properties:
      AutoScalingConfigurationArn:
        Fn::GetAtt:
          - AutoScaling
          - AutoScalingConfigurationArn
      HealthCheckConfiguration:
        HealthyThreshold: 1
        Interval: 10
        Path: /health
        Protocol: HTTP
        Timeout: 5
        UnhealthyThreshold: 5
      InstanceConfiguration:
        Cpu: 0.25 vCPU
        InstanceRoleArn:
          Fn::GetAtt:
            - InstanceRole3CCE2F1D
            - Arn
        Memory: 0.5 GB
      ServiceName: app-runner-container
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn:
            Fn::GetAtt:
              - AccessRoleEC309AE6
              - Arn
        AutoDeploymentsEnabled: false
        ImageRepository:
          ImageConfiguration:
            Port: "3000"
            RuntimeEnvironmentSecrets:
              - Name: API_KEY
                Value: arn:aws:ssm:eu-central-1:495599779087:parameter/hands-on-aws/containers/api-key
          ImageIdentifier:
            Fn::Join:
              - ""
              - - 495599779087.dkr.ecr.eu-central-1.
                - Ref: AWS::URLSuffix
                - /hands-on-containers:latest
          ImageRepositoryType: ECR
    Metadata:
      aws:cdk:path: AppRunnerStack/Service
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/6WNzWrDMBCEnyU6Flk1JvTgm5MHSLGPoZStvDabyCuhnwQj9O7FaaD03NMwwzczjWr2tap3cA+VHq+VoS+Vhwj6KuEePjNqr3p0NlC0fj1AQEmwqNxbg+csIIS04HhYRZuF88SaHJhOa5s4ila8CPlktkKnI1l+xEWKBRhmHN+tIU0YRHvOf7K180/2o8j/XREbYvx9eozK48QbWiQ45xMzepWPE3cp2kGDIZ6Plieak4dtbOMH9DfSWMpmTim6FItkO6K6hNdbs1dvqt5dAlHlE0daUPU/+g3SuLbBaAEAAA==
    Metadata:
      aws:cdk:path: AppRunnerStack/CDKMetadata/Default
Outputs:
  ServiceUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Fn::GetAtt:
              - Service
              - ServiceUrl
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

