Resources:
  DestinationBucket4BECDB47:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - ""
          - - Ref: AWS::AccountId
            - -cross-region-replication-destination-bucket
      Tags:
        - Key: aws-cdk:auto-delete-objects
          Value: "true"
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: S3CrossRegionReplicationStackStep1/DestinationBucket/Resource
  DestinationBucketPolicyFCD81088:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DestinationBucket4BECDB47
      PolicyDocument:
        Statement:
          - Action:
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:List*
              - s3:PutBucketPolicy
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
                  - Arn
            Resource:
              - Fn::GetAtt:
                  - DestinationBucket4BECDB47
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - DestinationBucket4BECDB47
                        - Arn
                    - /*
          - Action:
              - s3:GetBucketVersioning
              - s3:PutBucketVersioning
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - ReplicationRoleCE149CEC
                  - Arn
            Resource:
              Fn::GetAtt:
                - DestinationBucket4BECDB47
                - Arn
          - Action:
              - s3:ReplicateDelete
              - s3:ReplicateObject
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - ReplicationRoleCE149CEC
                  - Arn
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - DestinationBucket4BECDB47
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: S3CrossRegionReplicationStackStep1/DestinationBucket/Policy/Resource
  DestinationBucketAutoDeleteObjectsCustomResource8ECA4428:
    Type: Custom::S3AutoDeleteObjects
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F
          - Arn
      BucketName:
        Ref: DestinationBucket4BECDB47
    DependsOn:
      - DestinationBucketPolicyFCD81088
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: S3CrossRegionReplicationStackStep1/DestinationBucket/AutoDeleteObjectsCustomResource/Default
  CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: S3CrossRegionReplicationStackStep1/Custom::S3AutoDeleteObjectsCustomResourceProvider/Role
  CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-495599779087-eu-west-1
        S3Key: faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6.zip
      Timeout: 900
      MemorySize: 128
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
          - Arn
      Runtime: nodejs20.x
      Description:
        Fn::Join:
          - ""
          - - "Lambda function for auto-deleting objects in "
            - Ref: DestinationBucket4BECDB47
            - " S3 bucket."
    DependsOn:
      - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
    Metadata:
      aws:cdk:path: S3CrossRegionReplicationStackStep1/Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler
      aws:asset:path: asset.faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6
      aws:asset:property: Code
  ReplicationRoleCE149CEC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
        Version: "2012-10-17"
      Description: Role used to replicate across accounts for S3 buckets
    Metadata:
      aws:cdk:path: S3CrossRegionReplicationStackStep1/ReplicationRole/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/2WOT2/CMAzFPws+ojQbsMPUG2XngcoRTVNIPWRokyp2ilDU7z5BENqfk633/N7Pcz17nenZxJy5sM2paGmv01aMPSlz5s/EC52qaE8ouwT72/JuOoQSpqBgwMDkHTZQSoioIGDnB9NufEv2AiU0yBL8BRSYKP4NWxRc749ohXNk/FCrL5cJKo8cfuBuqJ9n2R8VmU6n2re4S1eODdQLeXd/zTDHDpvqAmWCPpCz1Jt2aa2PTn7dXCuW9hEdM+uqjqNaRRbf1cg+Bos7mEJ278IffxP8QA2GyjCqJTPKVsyB3EH9a1hH6aOMyvkG9ZGfhvlCv+jnyZGJihCdUIe6zvMbf+mtOaUBAAA=
    Metadata:
      aws:cdk:path: S3CrossRegionReplicationStackStep1/CDKMetadata/Default
Outputs:
  DestinationBucketName:
    Value:
      Ref: DestinationBucket4BECDB47
  DestinationBucketArn:
    Value:
      Fn::GetAtt:
        - DestinationBucket4BECDB47
        - Arn
  ReplicationRoleArn:
    Value:
      Fn::GetAtt:
        - ReplicationRoleCE149CEC
        - Arn
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

