Resources:
  DomainSG1DB71FAD:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpenSearch domain security group - inbound rules added by consumer stacks
      SecurityGroupEgress:
        - CidrIp: 255.255.255.255/32
          Description: Disallow all traffic
          FromPort: 252
          IpProtocol: icmp
          ToPort: 86
      VpcId:
        Fn::ImportValue: VpcSubnets:ExportsOutputRefVpc8378EB38272D6E3A
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/DomainSG/Resource
  DomainSlowSearchLogs5B35A97A:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/Domain/SlowSearchLogs/Resource
  DomainAppLogs21698C1B:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/Domain/AppLogs/Resource
  DomainESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87C3163ABF:
    Type: Custom::CloudwatchLogResourcePolicy
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd22872D164C4C
          - Arn
      Create:
        Fn::Join:
          - ""
          - - '{"service":"CloudWatchLogs","action":"putResourcePolicy","parameters":{"policyName":"ESLogPolicyc89fdd536052444e1c78129d031be82d8bdc097a87","policyDocument":"{\"Statement\":[{\"Action\":[\"logs:PutLogEvents\",\"logs:CreateLogStream\"],\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"es.amazonaws.com\"},\"Resource\":[\"'
            - Fn::GetAtt:
                - DomainSlowSearchLogs5B35A97A
                - Arn
            - \",\"
            - Fn::GetAtt:
                - DomainAppLogs21698C1B
                - Arn
            - \"]}],\"Version\":\"2012-10-17\"}"},"physicalResourceId":{"id":"ESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87"}}
      Update:
        Fn::Join:
          - ""
          - - '{"service":"CloudWatchLogs","action":"putResourcePolicy","parameters":{"policyName":"ESLogPolicyc89fdd536052444e1c78129d031be82d8bdc097a87","policyDocument":"{\"Statement\":[{\"Action\":[\"logs:PutLogEvents\",\"logs:CreateLogStream\"],\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"es.amazonaws.com\"},\"Resource\":[\"'
            - Fn::GetAtt:
                - DomainSlowSearchLogs5B35A97A
                - Arn
            - \",\"
            - Fn::GetAtt:
                - DomainAppLogs21698C1B
                - Arn
            - \"]}],\"Version\":\"2012-10-17\"}"},"physicalResourceId":{"id":"ESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87"}}
      Delete: '{"service":"CloudWatchLogs","action":"deleteResourcePolicy","parameters":{"policyName":"ESLogPolicyc89fdd536052444e1c78129d031be82d8bdc097a87"},"ignoreErrorCodesMatching":"ResourceNotFoundException"}'
      InstallLatestAwsSdk: false
    DependsOn:
      - DomainESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87CustomResourcePolicyEDC4EF78
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/Domain/ESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87/Resource/Default
  DomainESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87CustomResourcePolicyEDC4EF78:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:DeleteResourcePolicy
              - logs:PutResourcePolicy
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: DomainESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87CustomResourcePolicyEDC4EF78
      Roles:
        - Ref: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/Domain/ESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87/CustomResourcePolicy/Resource
  Domain66AC69E0:
    Type: AWS::OpenSearchService::Domain
    Properties:
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 2
        InstanceType: t3.small.search
        MultiAZWithStandbyEnabled: false
        ZoneAwarenessConfig:
          AvailabilityZoneCount: 2
        ZoneAwarenessEnabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: Policy-Min-TLS-1-2-2019-07
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp3
      EncryptionAtRestOptions:
        Enabled: true
      EngineVersion: OpenSearch_2.19
      LogPublishingOptions:
        SEARCH_SLOW_LOGS:
          CloudWatchLogsLogGroupArn:
            Fn::GetAtt:
              - DomainSlowSearchLogs5B35A97A
              - Arn
          Enabled: true
        ES_APPLICATION_LOGS:
          CloudWatchLogsLogGroupArn:
            Fn::GetAtt:
              - DomainAppLogs21698C1B
              - Arn
          Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      VPCOptions:
        SecurityGroupIds:
          - Fn::GetAtt:
              - DomainSG1DB71FAD
              - GroupId
        SubnetIds:
          - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet1SubnetE48C57379FE391D3
          - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet2Subnet16364B914643ED68
    DependsOn:
      - DomainESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87CustomResourcePolicyEDC4EF78
      - DomainESLogGroupPolicyc89fdd536052444e1c78129d031be82d8bdc097a87C3163ABF
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/Domain/Resource
  DomainAccessPolicyEE735B04:
    Type: Custom::OpenSearchAccessPolicy
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd22872D164C4C
          - Arn
      Create:
        Fn::Join:
          - ""
          - - '{"action":"updateDomainConfig","service":"OpenSearch","parameters":{"DomainName":"'
            - Ref: Domain66AC69E0
            - '","AccessPolicies":"{\"Statement\":[{\"Action\":\"es:*\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::495599779087:root\"},\"Resource\":[\"'
            - Fn::GetAtt:
                - Domain66AC69E0
                - Arn
            - \",\"
            - Fn::GetAtt:
                - Domain66AC69E0
                - Arn
            - /*\"]}],\"Version\":\"2012-10-17\"}"},"outputPaths":["DomainConfig.AccessPolicies"],"physicalResourceId":{"id":"
            - Ref: Domain66AC69E0
            - AccessPolicy"}}
      Update:
        Fn::Join:
          - ""
          - - '{"action":"updateDomainConfig","service":"OpenSearch","parameters":{"DomainName":"'
            - Ref: Domain66AC69E0
            - '","AccessPolicies":"{\"Statement\":[{\"Action\":\"es:*\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::495599779087:root\"},\"Resource\":[\"'
            - Fn::GetAtt:
                - Domain66AC69E0
                - Arn
            - \",\"
            - Fn::GetAtt:
                - Domain66AC69E0
                - Arn
            - /*\"]}],\"Version\":\"2012-10-17\"}"},"outputPaths":["DomainConfig.AccessPolicies"],"physicalResourceId":{"id":"
            - Ref: Domain66AC69E0
            - AccessPolicy"}}
      InstallLatestAwsSdk: false
    DependsOn:
      - DomainAccessPolicyCustomResourcePolicyE61F1845
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/Domain/AccessPolicy/Resource/Default
  DomainAccessPolicyCustomResourcePolicyE61F1845:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: es:UpdateDomainConfig
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - Domain66AC69E0
                - Arn
        Version: "2012-10-17"
      PolicyName: DomainAccessPolicyCustomResourcePolicyE61F1845
      Roles:
        - Ref: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/Domain/AccessPolicy/CustomResourcePolicy/Resource
  AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/AWS679f53fac002430cb0da5b7982bd2287/ServiceRole/Resource
  AWS679f53fac002430cb0da5b7982bd22872D164C4C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-495599779087-eu-central-1
        S3Key: 56f7467bbde8a5efebcf57ae9e460027607099bab9f844669dcf5d800172ee5a.zip
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
          - Arn
      Runtime: nodejs22.x
      Timeout: 120
    DependsOn:
      - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/AWS679f53fac002430cb0da5b7982bd2287/Resource
      aws:asset:path: asset.56f7467bbde8a5efebcf57ae9e460027607099bab9f844669dcf5d800172ee5a
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/+VVTW/cOAz9LdWxULxBUvQwNyeb7hbotkUcYIEOBgFHZhw1smSI1Awcw/+9kCy7TrYt2luBPXn0SPHx44lzVpy9Oi1OX8CRTlT9cGL0vhgqBvUg4Ui3A6qzYqhQBa+5/8u70G0HceiU2IiXQooaSXndsXY2I2CMO5bGfAi8d8HWYnMHhnDcycs7+yTQKF2HlhC8uif0B62wGP50LWgbOdDT16gKOlCae7EZRA0M712NNOeQz28tMViFN32H2dQCMfq1cxsM6/LxX833FYOt9/2Vhb3BJU8pcE+R5uBMaLHSj3OwCcjRm+5cjFI8OovlETxapHQL52jsA0oBB9AG9tpo7j85i5cuWE7xRhnbWIW9RSax2Q6Clt+J7qXYjTu56jWtm5fddlKgvXNe4d/MEZxoravxxsW6r6zyfZ7PZMMFKfkaif+T9SiFcU2jbRNNZNyxSjN655qrZ9V13XNwlMJj6w5gPjqjVS82USPsXS9GOQio61IpJEpWjanycTepY5r9KI1rqBjeuWbWm0dGO9VwfhrDPAXS5dl9lAbafQ3FUGnbGGRn3wSrovN2ECHoOrdzcvsYfOdo0Qu2zvermbNu0QXOJ+/MbDCZLh/vMsV7aBe5LINbz3lSs6tnr3uwtUE/EwQbGbNAUrv+QYao8CyL2OPdt01JMfJ/UONOrib6W5WTlDgnN0oNbTFM7yC+bwbGFm2OmQusVmh6Cj+AmUHd37jrVNN2nvd34F+g+/m4qcCpIhnx7SCAKLRYX6Td3Hltle7AlEotq05mn3ihVMt/xRj3s4UG6/UyeIL1pc++q4zeWqMtzuvlWbrfMqakI/ko6fwWiJCpKONH0nlxEdQD8gXE3a8CsWtvPZILXiEV5ZEuE3adIfn0uIgyUcw+KXbFEHdoNHwI3AUeZVzLxWf643D2qnhdnL74TFqfZAEV19P3Cwg2EmeRBwAA
    Metadata:
      aws:cdk:path: RdsOpensearchOpenSearch/CDKMetadata/Default
Outputs:
  DomainEndpoint:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Fn::GetAtt:
              - Domain66AC69E0
              - DomainEndpoint
  DomainName:
    Value:
      Ref: Domain66AC69E0
  DomainArn:
    Value:
      Fn::GetAtt:
        - Domain66AC69E0
        - Arn
  ExportsOutputFnGetAttDomain66AC69E0ArnA2ECE2E0:
    Value:
      Fn::GetAtt:
        - Domain66AC69E0
        - Arn
    Export:
      Name: RdsOpensearchOpenSearch:ExportsOutputFnGetAttDomain66AC69E0ArnA2ECE2E0
  ExportsOutputFnGetAttDomainSG1DB71FADGroupIdA7C3AABC:
    Value:
      Fn::GetAtt:
        - DomainSG1DB71FAD
        - GroupId
    Export:
      Name: RdsOpensearchOpenSearch:ExportsOutputFnGetAttDomainSG1DB71FADGroupIdA7C3AABC
  ExportsOutputFnGetAttDomain66AC69E0DomainEndpoint34F0DAB2:
    Value:
      Fn::GetAtt:
        - Domain66AC69E0
        - DomainEndpoint
    Export:
      Name: RdsOpensearchOpenSearch:ExportsOutputFnGetAttDomain66AC69E0DomainEndpoint34F0DAB2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

