Resources:
  OrdersTable315BB997:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: orders-cdc-demo
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: DynamoDBLambda/OrdersTable/Resource
  StreamDeadLetterQueueDA607735:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: orders-cdc-dlq
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamDeadLetterQueue/Resource
  StreamProcessorServiceRole38F6612A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamProcessor/ServiceRole/Resource
  StreamProcessorServiceRoleDefaultPolicy25F89E31:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:SendMessage
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - StreamDeadLetterQueueDA607735
                - Arn
          - Action: dynamodb:ListStreams
            Effect: Allow
            Resource: "*"
          - Action:
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - OrdersTable315BB997
                - StreamArn
        Version: "2012-10-17"
      PolicyName: StreamProcessorServiceRoleDefaultPolicy25F89E31
      Roles:
        - Ref: StreamProcessorServiceRole38F6612A
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamProcessor/ServiceRole/DefaultPolicy/Resource
  StreamProcessorA985C501:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-495599779087-eu-central-1
        S3Key: 3873589a508a790bfee7fd37567a5416ded69c46c98554bcb8e51be4312a1ebc.zip
      Environment:
        Variables:
          TABLE_NAME:
            Ref: OrdersTable315BB997
      FunctionName: orders-stream-processor
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - StreamProcessorServiceRole38F6612A
          - Arn
      Runtime: nodejs20.x
      Timeout: 30
    DependsOn:
      - StreamProcessorServiceRoleDefaultPolicy25F89E31
      - StreamProcessorServiceRole38F6612A
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamProcessor/Resource
      aws:asset:path: asset.3873589a508a790bfee7fd37567a5416ded69c46c98554bcb8e51be4312a1ebc
      aws:asset:is-bundled: true
      aws:asset:property: Code
  StreamProcessorDynamoDBEventSourceDynamoDBLambdaOrdersTable348202BF814358FF:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 5
      BisectBatchOnFunctionError: true
      DestinationConfig:
        OnFailure:
          Destination:
            Fn::GetAtt:
              - StreamDeadLetterQueueDA607735
              - Arn
      EventSourceArn:
        Fn::GetAtt:
          - OrdersTable315BB997
          - StreamArn
      FunctionName:
        Ref: StreamProcessorA985C501
      MaximumRetryAttempts: 3
      StartingPosition: LATEST
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamProcessor/DynamoDBEventSource:DynamoDBLambdaOrdersTable348202BF/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/8VUS0/jMBD+LfiITBYB2kNvKZQVWvqg6QqtKlQ59jQYHDvY40KI8t9XdpMWFi3itqexvxnPfON5nCQnZ8fJ8QF7dkdcPB4pmSdNhow/UvbsVo2oNSuNyJNmwXIFy4ZgkBNWAhmQQ0JJxSxKlEb/hJoMGqL3KqyrcMxIS0kulZK6GBsRoFn6ezUbzVfz0c2vUbYglDi0wEoyIJPR7SqdXKym1xerq3H6Y5QRSiyUZsPUzCjJazIgAhxaU5P2jp6vdaTWUvfkkubGgw80n4J8Q/NzD/FVSxUrc8FW2gh4cMkkikuveUhv2ZB1d3zjFjTaujvfMy0U2D6g1yj3XyFLMB53rzbSGl2C7pHcaxH+J/wgvCBYzdTYCK/ARYuWEr79unBuWvp/2bR3VLIyaeYm9gRzzpcghrEBKis1lxVTKefG73xubcKDNNLu0yqZZgWIWBgZ/C+bd1id2s72LmTNhFiYWR+iL+ey6bSIjN9faSU17HTkkHxB+bnff2tj/4S06BYOHnfBFiZoPnD4CAuRIUMINXDvwn4VjjS2DFrqTlfMOUCXpEFQd5oMPX8EHDIHXZcnzfla981NRxvQmBlvOYxZVUldxFG3Bey6ZG/RV4SSEtBK7s6NXsuiw5yvKmMxO53qSyaVt3ABDqVm26qj9UBJzpDfZ/K178hcOuA4DOhUj6w1trd0GBaMLmbGya5vrtPFdmlYCJHiqyuEsgvnenLsJaqkLm6lFuZ5j8+BGyvSYr8d0NYpIpQVuv1iY0qBkq+R+SXjaPpxMn1q/UD5Mld/xwEd9pLobmupEKx7dxtpbutqPw2xiB9L0bZ0Di4isWNorGqGrJC6CE+mHiuPLQ2LK3lw3zYnZ8n35PjgwUl51I1+Mt/KP6TV66/yBQAA
    Metadata:
      aws:cdk:path: DynamoDBLambda/CDKMetadata/Default
Outputs:
  TableName:
    Value:
      Ref: OrdersTable315BB997
  FunctionName:
    Value:
      Ref: StreamProcessorA985C501
  DLQUrl:
    Value:
      Ref: StreamDeadLetterQueueDA607735
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

