Resources:
  OrdersTable315BB997:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      Replicas:
        - Region: eu-central-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: orders-cdc-demo
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: DynamoDBLambda/OrdersTable/Resource
  StreamDeadLetterQueueDA607735:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: orders-cdc-dlq
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamDeadLetterQueue/Resource
  StreamProcessorServiceRole38F6612A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamProcessor/ServiceRole/Resource
  StreamProcessorServiceRoleDefaultPolicy25F89E31:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:SendMessage
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - StreamDeadLetterQueueDA607735
                - Arn
          - Action:
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:ListStreams
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - OrdersTable315BB997
                - StreamArn
        Version: "2012-10-17"
      PolicyName: StreamProcessorServiceRoleDefaultPolicy25F89E31
      Roles:
        - Ref: StreamProcessorServiceRole38F6612A
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamProcessor/ServiceRole/DefaultPolicy/Resource
  StreamProcessorA985C501:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-495599779087-eu-central-1
        S3Key: 3873589a508a790bfee7fd37567a5416ded69c46c98554bcb8e51be4312a1ebc.zip
      Environment:
        Variables:
          TABLE_NAME:
            Ref: OrdersTable315BB997
      FunctionName: orders-stream-processor
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - StreamProcessorServiceRole38F6612A
          - Arn
      Runtime: nodejs20.x
      Timeout: 30
    DependsOn:
      - StreamProcessorServiceRoleDefaultPolicy25F89E31
      - StreamProcessorServiceRole38F6612A
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamProcessor/Resource
      aws:asset:path: asset.3873589a508a790bfee7fd37567a5416ded69c46c98554bcb8e51be4312a1ebc
      aws:asset:is-bundled: true
      aws:asset:property: Code
  StreamProcessorDynamoDBEventSourceDynamoDBLambdaOrdersTable348202BF814358FF:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 5
      BisectBatchOnFunctionError: true
      DestinationConfig:
        OnFailure:
          Destination:
            Fn::GetAtt:
              - StreamDeadLetterQueueDA607735
              - Arn
      EventSourceArn:
        Fn::GetAtt:
          - OrdersTable315BB997
          - StreamArn
      FunctionName:
        Ref: StreamProcessorA985C501
      MaximumRetryAttempts: 3
      StartingPosition: LATEST
    Metadata:
      aws:cdk:path: DynamoDBLambda/StreamProcessor/DynamoDBEventSource:DynamoDBLambdaOrdersTable348202BF/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/8VUUU/jMAz+LZdHFHpooHvYW4GB0MHG0el4mNDkJl4JpElJnEGp+t9P6doNDh3i7Z7i2I79OZ/tUTI6OkgOvsGz3xfycV+rPGkyAvHI4dkvG1kbKK3Mk2YOucbfo0XDKEpTKJGN2R7jrAJHipQ1P7Fm44aZnYnqKooZaznLldbKFL1lEzgjh1CyMZtObpfp9HQ5uzxdXlyl55OMceawtGvQ11YrUbMxk+jJ2Zq1d/xkZc61zUF3sFrun3zS/AoYcNGwp3i+Afh5nO5VyzWUuYSlsRIffDLtjrNgRCxs0bBVL74Ji4Zc3cv3YKRGNyQMhtTuE1SJNtD21Vo5a0o0gyYPRm5+pmH4QugM6Csrg0bfebScCSuxl5uW/1807R1XUCbNjdXxs8H7UKI87qivnDJCVaBTIWzYxtz4xAdpB3soqwQDBcqOGBXjL5p3ujp1ve9drBqknNvrIcVA56LprUQg7i+MVga3NrbHvmD8PO6/rV3/xLL4Rh0jbpPNbbR8wPBRLWVGQBg58O/SflXdwdggaLk/XIL3SD5J48H9YXIcxCPSMXjsuzxpTlZmaG4+WaOhzAYn8AqqSpmiG3JX4LZLdh4DI5yVSE4Jf2LNSg1T7UNVWUfZ4cycgdLB4Sl6UgY2rJMLyFkOJO4z9Tp0ZK48CjqO2pmZOGfd4OkprhZTXFuv+r65TOeTbN4NdczUvbogLPt0fgAHL51JmeJWGWmfd/obFNbJtNhtB3J1SoRlRX630kBr1Oq1Q34GguwwTnYobRioUOb67zxo4l6S/W2lNKHz724TI1xd7aahI/EjFW3LOx4zgkKZIjrNAlWBWh5XVfLgv69HR8mP5ODbg1dqvx/25GZz/gG+EcxV4AUAAA==
    Metadata:
      aws:cdk:path: DynamoDBLambda/CDKMetadata/Default
Outputs:
  TableName:
    Value:
      Ref: OrdersTable315BB997
  FunctionName:
    Value:
      Ref: StreamProcessorA985C501
  DLQUrl:
    Value:
      Ref: StreamDeadLetterQueueDA607735
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

