Resources:
  GlobalTable89F068B2:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: origin
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: byOrigin
          KeySchema:
            - AttributeName: origin
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      Replicas:
        - GlobalSecondaryIndexes:
            - IndexName: byOrigin
          Region: us-east-1
        - GlobalSecondaryIndexes:
            - IndexName: byOrigin
          Region: eu-central-1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: global-content
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: DynamodbGlobalDatabase/GlobalTable/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/61QwUrEMBD9lp2jpLGUxUOvHkQEla14WYpMmmyZ3TQpSbprCPl3aSt4UATB07zhvXkzbypebUtebvDii06eCk2CpyZgd2J48W8yGhysFDy9oNDqtdonCDN6xEFBDVfAYEQXKJA1DypCncB8USGOM2wgM/DWhd8VgrQm038yTg32jPrZauoi1CCVD87GhRk1deih3idwqidrlpncMui1Fagb1Vkj0cV7I9W7WpU047/endvMEqCUdz8Y/4Ptbs3yPUpu2e3BrFuX3+e5f5rCOIXMjJWKH/31udryG15ujp6ocJMJNCi+W+sHbXfEDdsBAAA=
    Metadata:
      aws:cdk:path: DynamodbGlobalDatabase/CDKMetadata/Default
Outputs:
  TableName:
    Value:
      Ref: GlobalTable89F068B2
  RegionEU:
    Value:
      Ref: AWS::Region
  RegionUS:
    Value: us-east-1
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

