Resources:
  DbSG0BE6ACB3:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS PostgreSQL security group
      VpcId:
        Fn::ImportValue: VpcSubnets:ExportsOutputRefVpc8378EB38272D6E3A
    Metadata:
      aws:cdk:path: RdsPostgres/DbSG/Resource
  DbSGfromRdsPostgresDbSGA73F2DDAIndirectPortFB88DABB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connections to the database Instance from the Proxy
      FromPort:
        Fn::GetAtt:
          - InstanceC1063A87
          - Endpoint.Port
      GroupId:
        Fn::GetAtt:
          - DbSG0BE6ACB3
          - GroupId
      IpProtocol: tcp
      SourceSecurityGroupId:
        Fn::GetAtt:
          - DbSG0BE6ACB3
          - GroupId
      ToPort:
        Fn::GetAtt:
          - InstanceC1063A87
          - Endpoint.Port
    Metadata:
      aws:cdk:path: RdsPostgres/DbSG/from RdsPostgresDbSGA73F2DDA:{IndirectPort}
  DbSGtoRdsPostgresDbSGA73F2DDAIndirectPort2856866F:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: Allow connections to the database Instance from the Proxy
      DestinationSecurityGroupId:
        Fn::GetAtt:
          - DbSG0BE6ACB3
          - GroupId
      FromPort:
        Fn::GetAtt:
          - InstanceC1063A87
          - Endpoint.Port
      GroupId:
        Fn::GetAtt:
          - DbSG0BE6ACB3
          - GroupId
      IpProtocol: tcp
      ToPort:
        Fn::GetAtt:
          - InstanceC1063A87
          - Endpoint.Port
    Metadata:
      aws:cdk:path: RdsPostgres/DbSG/to RdsPostgresDbSGA73F2DDA:{IndirectPort}
  BastionToDb:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: PostgreSQL from bastion (SSM tunnel)
      FromPort: 5432
      GroupId:
        Fn::GetAtt:
          - DbSG0BE6ACB3
          - GroupId
      IpProtocol: tcp
      SourceSecurityGroupId:
        Fn::ImportValue: SsmBastion:ExportsOutputFnGetAttBastionSGEBD2A3B1GroupId0BE655F5
      ToPort: 5432
    Metadata:
      aws:cdk:path: RdsPostgres/BastionToDb
  InstanceSubnetGroupF2CBA54F:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Instance database
      SubnetIds:
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet1SubnetE48C57379FE391D3
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet2Subnet16364B914643ED68
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet3Subnet6840A2D4F9E008CF
    Metadata:
      aws:cdk:path: RdsPostgres/Instance/SubnetGroup/Default
  RdsPostgresInstanceSecret7DB0E4B03fdaad7efa858a3daf9490cf0a702aeb:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description:
        Fn::Join:
          - ""
          - - "Generated by the CDK for stack: "
            - Ref: AWS::StackName
      GenerateSecretString:
        ExcludeCharacters: " %+~`#$&*()|[]{}:;<>?!'/@\"\\"
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate: '{"username":"postgres"}'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: RdsPostgres/Instance/Secret/Resource
  InstanceSecretAttachment83BEE581:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: RdsPostgresInstanceSecret7DB0E4B03fdaad7efa858a3daf9490cf0a702aeb
      TargetId:
        Ref: InstanceC1063A87
      TargetType: AWS::RDS::DBInstance
    Metadata:
      aws:cdk:path: RdsPostgres/Instance/Secret/Attachment/Resource
  InstanceC1063A87:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      BackupRetentionPeriod: 1
      CopyTagsToSnapshot: true
      DBInstanceClass: db.t4g.micro
      DBName: demo
      DBSubnetGroupName:
        Ref: InstanceSubnetGroupF2CBA54F
      DeletionProtection: false
      Engine: postgres
      EngineVersion: "17.7"
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: RdsPostgresInstanceSecret7DB0E4B03fdaad7efa858a3daf9490cf0a702aeb
            - :SecretString:password::}}
      MasterUsername: postgres
      MaxAllocatedStorage: 100
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp3
      VPCSecurityGroups:
        - Fn::GetAtt:
            - DbSG0BE6ACB3
            - GroupId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: RdsPostgres/Instance/Resource
  InstanceProxyIAMRoleA5CFBEF1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: rds.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: RdsPostgres/Instance/Proxy/IAMRole/Resource
  InstanceProxyIAMRoleDefaultPolicy4E598572:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - secretsmanager:DescribeSecret
              - secretsmanager:GetSecretValue
            Effect: Allow
            Resource:
              Ref: InstanceSecretAttachment83BEE581
        Version: "2012-10-17"
      PolicyName: InstanceProxyIAMRoleDefaultPolicy4E598572
      Roles:
        - Ref: InstanceProxyIAMRoleA5CFBEF1
    Metadata:
      aws:cdk:path: RdsPostgres/Instance/Proxy/IAMRole/DefaultPolicy/Resource
  InstanceProxyA39A17AC:
    Type: AWS::RDS::DBProxy
    Properties:
      Auth:
        - AuthScheme: SECRETS
          ClientPasswordAuthType: POSTGRES_SCRAM_SHA_256
          IAMAuth: DISABLED
          SecretArn:
            Ref: InstanceSecretAttachment83BEE581
      DBProxyName: RdsPostgresInstanceProxy78F689E2
      EngineFamily: POSTGRESQL
      IdleClientTimeout: 900
      RequireTLS: true
      RoleArn:
        Fn::GetAtt:
          - InstanceProxyIAMRoleA5CFBEF1
          - Arn
      VpcSecurityGroupIds:
        - Fn::GetAtt:
            - DbSG0BE6ACB3
            - GroupId
      VpcSubnetIds:
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet1SubnetE48C57379FE391D3
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet2Subnet16364B914643ED68
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet3Subnet6840A2D4F9E008CF
    Metadata:
      aws:cdk:path: RdsPostgres/Instance/Proxy/Resource
  InstanceProxyProxyTargetGroupE5DB070D:
    Type: AWS::RDS::DBProxyTargetGroup
    Properties:
      ConnectionPoolConfigurationInfo:
        ConnectionBorrowTimeout: 30
        MaxConnectionsPercent: 90
        MaxIdleConnectionsPercent: 50
      DBInstanceIdentifiers:
        - Ref: InstanceC1063A87
      DBProxyName:
        Ref: InstanceProxyA39A17AC
      TargetGroupName: default
    Metadata:
      aws:cdk:path: RdsPostgres/Instance/Proxy/ProxyTargetGroup
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/6VV227jNhD9luXjQlED73Yf/KZ4b8a2jSG5fTGMYExNFCYUqQ7JOK6gfy94kVZbOwWKPpEazu2cOaQW+eL9dX79Bo7mitdPV1Ic8r6ywJ8yOJq7Hvki7yvkjoQ9fSHtul3PnjvOluwty1iNhpPorNAqWUBKfSykvHX2oJ2q2fIepMEh6xnU9Vo1hMaUTiJb7nxAP2R+CU775PXpFSdLDvfDPlvdqx9aOjOkMmf2mHjIqDZ5/xEsHMDgWhkLiuOuZ6gaoZAtx9321GHCFQ1/IJmAtWf3TsrpM7i08Khpbhoy1gFBixYp1P8MrZCn5G6EaiT+bpBKbcFTWHSdFBxmbMaqP4a5rtNkTYlQlxgCboA/uc5MM7kHJ61PrKDFsRORYM4wfZ/jc8crd1BojYdmwjY5ro2WYLH2OcycTBOHs89Y66QVxV9p1BnjhDUqK0BOPSWufxsbikLhPnFlNUEzmk38SsWb7l0g9qW47H0IyEu0vtzEGmGrn0FutBTc01ajsaRPgRuJ3nFD2iKPIVGf+ywSMGr8XNn/ma1/tvGWRe1+vJmVykYZVsgJbRAhp1Mo/A2noYfDGXsUJ19iI7QyacY9c/OhXwi7lBtfuHQ1rh6AgFskMysBHG/VBow5aqpXJCySgNUDqAYNW/r7eLmVhHO8WhPIDemX065nnV+3QA3a/6FFCj5JhK9ok/BPJwi3v1Rjv1wKVHYEVTj7kLJvbqvtl/JTdVetyuLXu+prcbf4+YNXmSbSx61oUTs7XfaXlVYqishskDiq2dm6lvjqufCHoYt5zpG0wNFsG2kKsIYsoW5BQYOU9/GFI7RZXKJzYS3whxaV11MMSaXtd86nh/RC2JAJaPO+1NI/i2CMa7G+OfmBdCQUFx3IgnPtJkzRxwcUfLo0Q3rQt3ozRo23YdcP8bkPNddKCoXTmR/dvx+G3n21LNrjbyIFbLU/Octzbq7ryoJFj9iklkLimHMY/P7W2c7ZIVO6xvzR/PS8eJ9/yK/fPBohrsgpK1rMy7j+DYL3zQ9OBwAA
    Metadata:
      aws:cdk:path: RdsPostgres/CDKMetadata/Default
Outputs:
  DbEndpoint:
    Value:
      Fn::GetAtt:
        - InstanceC1063A87
        - Endpoint.Address
  DbPort:
    Value:
      Fn::GetAtt:
        - InstanceC1063A87
        - Endpoint.Port
  ProxyEndpoint:
    Value:
      Fn::GetAtt:
        - InstanceProxyA39A17AC
        - Endpoint
  SecretArn:
    Value:
      Ref: InstanceSecretAttachment83BEE581
  DatabaseName:
    Value: demo
  MultiAz:
    Value: "false"
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

