Resources:
  DbSG0BE6ACB3:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS PostgreSQL read-replicas security group
      SecurityGroupEgress:
        - CidrIp: 255.255.255.255/32
          Description: Disallow all traffic
          FromPort: 252
          IpProtocol: icmp
          ToPort: 86
      VpcId:
        Fn::ImportValue: VpcSubnets:ExportsOutputRefVpc8378EB38272D6E3A
    Metadata:
      aws:cdk:path: RdsReadReplicas/DbSG/Resource
  PrimarySubnetGroupF5983FB5:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Primary database
      SubnetIds:
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet1SubnetE48C57379FE391D3
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet2Subnet16364B914643ED68
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet3Subnet6840A2D4F9E008CF
    Metadata:
      aws:cdk:path: RdsReadReplicas/Primary/SubnetGroup/Default
  RdsReadReplicasPrimarySecret3DB975EC3fdaad7efa858a3daf9490cf0a702aeb:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description:
        Fn::Join:
          - ""
          - - "Generated by the CDK for stack: "
            - Ref: AWS::StackName
      GenerateSecretString:
        ExcludeCharacters: " %+~`#$&*()|[]{}:;<>?!'/@\"\\"
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate: '{"username":"postgres"}'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: RdsReadReplicas/Primary/Secret/Resource
  PrimarySecretAttachment0450815C:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: RdsReadReplicasPrimarySecret3DB975EC3fdaad7efa858a3daf9490cf0a702aeb
      TargetId:
        Ref: Primary503D6591
      TargetType: AWS::RDS::DBInstance
    Metadata:
      aws:cdk:path: RdsReadReplicas/Primary/Secret/Attachment/Resource
  Primary503D6591:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      BackupRetentionPeriod: 1
      CopyTagsToSnapshot: true
      DBInstanceClass: db.t4g.micro
      DBName: demo
      DBSubnetGroupName:
        Ref: PrimarySubnetGroupF5983FB5
      DeletionProtection: false
      Engine: postgres
      EngineVersion: "17.7"
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: RdsReadReplicasPrimarySecret3DB975EC3fdaad7efa858a3daf9490cf0a702aeb
            - :SecretString:password::}}
      MasterUsername: postgres
      MaxAllocatedStorage: 100
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp3
      VPCSecurityGroups:
        - Fn::GetAtt:
            - DbSG0BE6ACB3
            - GroupId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: RdsReadReplicas/Primary/Resource
  Replica1SubnetGroup5FD03996:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Replica1 database
      SubnetIds:
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet1SubnetE48C57379FE391D3
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet2Subnet16364B914643ED68
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcIsolatedSubnet3Subnet6840A2D4F9E008CF
    Metadata:
      aws:cdk:path: RdsReadReplicas/Replica1/SubnetGroup/Default
  Replica1911D769F:
    Type: AWS::RDS::DBInstance
    Properties:
      CopyTagsToSnapshot: true
      DBInstanceClass: db.t4g.micro
      DBSubnetGroupName:
        Ref: Replica1SubnetGroup5FD03996
      DeletionProtection: false
      MaxAllocatedStorage: 100
      PubliclyAccessible: false
      SourceDBInstanceIdentifier:
        Fn::Join:
          - ""
          - - "arn:aws:rds:eu-central-1:495599779087:db:"
            - Ref: Primary503D6591
      StorageType: gp3
      VPCSecurityGroups:
        - Fn::GetAtt:
            - DbSG0BE6ACB3
            - GroupId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: RdsReadReplicas/Replica1/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/7VUwW7bMAz9lupYuF6RFTvklqbYUAxYi6TbJSgKRmZctbIkkFTSzPC/D5btzO1y6YCeJFMkH/n46Ek+uTjPz09gx2e6eD6zZp3XSwH9nMGOH2rUk7xeoo5kZP+NfAyrWm2DVlN1qjJVIGsyQYx3vQWs9buZtTdR1j66Qk03YBmb+2y+ca8SNRkVnNdXILAGxmvHAk7jqlboSuNQTYfb3T5gn74z/ELiBFmrTbT28JlcKnjyNDY1mQpAUKEgJeSvUBm7793ZuNLiT0ZaeIG2k1kI1mgYNdWhvg6LIXgSXiAUC0wBl6CfY+ADNRuIVtrEDiocKjF9m6Oe/tK5DXoZ1w6F29Y4XXvHa/YWBIs2B49pZDVdqVN1n6kqWjGz3z3jmdKEBToxYA819Vz/GArq5qXbxEvxBOVg5u6rBy/D50Tsy+y49zp1vkBp4Q6sEVZ+C/bWW6Nb2gpkIb9P3FhsHW/JC+ouZJBJR8AgtX8F9m623pbRjuGjEieVX12OesgGfS9RE0pSt6Z9Av6OBzWlx9FYqJPUAkvjHR+qjmM1HQk7lhtftI0Fzh+BQAsSjyBA4427Beadp2JORpAMzB/BlchqKhTxeCl9n8POZm+XeLQVq1qxj6TxrU9fxgcuxPtE/F9ybbJuBlyBgxIpr7vfHKFk3XEHVKLMREA/VuhaBXQhPayk9xGtx8Oapn27iRKiNJnzBeZP/Gk7uci/5OcnT2zMGUUnpsJ80Z1/AMEZQRjbBQAA
    Metadata:
      aws:cdk:path: RdsReadReplicas/CDKMetadata/Default
Outputs:
  DbPort:
    Value:
      Fn::GetAtt:
        - Primary503D6591
        - Endpoint.Port
  DatabaseName:
    Value: demo
  ExportsOutputFnGetAttDbSG0BE6ACB3GroupIdE6F8FAFE:
    Value:
      Fn::GetAtt:
        - DbSG0BE6ACB3
        - GroupId
    Export:
      Name: RdsReadReplicas:ExportsOutputFnGetAttDbSG0BE6ACB3GroupIdE6F8FAFE
  ExportsOutputRefPrimarySecretAttachment0450815C1C8331A7:
    Value:
      Ref: PrimarySecretAttachment0450815C
    Export:
      Name: RdsReadReplicas:ExportsOutputRefPrimarySecretAttachment0450815C1C8331A7
  ExportsOutputRefPrimary503D659132D8A060:
    Value:
      Ref: Primary503D6591
    Export:
      Name: RdsReadReplicas:ExportsOutputRefPrimary503D659132D8A060
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

