Resources:
  VpcLinkSG3BF39CE1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for API Gateway VPC Link
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId:
        Fn::ImportValue: VpcSubnets:ExportsOutputRefVpc8378EB38272D6E3A
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/VpcLinkSG/Resource
  TaskSgIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow traffic from VPC Link only
      FromPort: 3000
      GroupId:
        Fn::ImportValue: EcsFargateComputeStack:ExportsOutputFnGetAttTaskSG7164C6FAGroupIdEA038E97
      IpProtocol: tcp
      SourceSecurityGroupId:
        Fn::GetAtt:
          - VpcLinkSG3BF39CE1
          - GroupId
      ToPort: 3000
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/TaskSgIngress
  VpcLink42ED6FF0:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: EcsFargateNetworkingStackVpcLink35B5E076
      SecurityGroupIds:
        - Fn::GetAtt:
            - VpcLinkSG3BF39CE1
            - GroupId
      SubnetIds:
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcPrivateSubnet1Subnet536B997AFD4CC940
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcPrivateSubnet2Subnet3788AAA1380949A3
        - Fn::ImportValue: VpcSubnets:ExportsOutputRefVpcPrivateSubnet3SubnetF258B56EC7CF32DD
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/VpcLink/Resource
  ApiAccessLogGroupCEA70788:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /apigateway/ecs-fargate-apigw
      RetentionInDays: 7
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/ApiAccessLogGroup/Resource
  HttpApiF5A9A8A7:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: HttpApi
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/HttpApi/Resource
  HttpApiDefaultStage3EEB07D6:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      AccessLogSettings:
        DestinationArn:
          Fn::GetAtt:
            - ApiAccessLogGroupCEA70788
            - Arn
        Format: $context.requestId $context.httpMethod $context.path $context.status $context.integrationLatency
      ApiId:
        Ref: HttpApiF5A9A8A7
      AutoDeploy: true
      StageName: $default
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/HttpApi/DefaultStage/Resource
  HttpApiGEThealthCloudMapIntegrationF6876C3A:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: HttpApiF5A9A8A7
      ConnectionId:
        Ref: VpcLink42ED6FF0
      ConnectionType: VPC_LINK
      IntegrationMethod: ANY
      IntegrationType: HTTP_PROXY
      IntegrationUri:
        Fn::ImportValue: EcsFargateComputeStack:ExportsOutputFnGetAttServiceCloudmapService046058A4Arn1A865595
      PayloadFormatVersion: "1.0"
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/HttpApi/GET--health/CloudMapIntegration/Resource
  HttpApiGEThealthAB1F4856:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: HttpApiF5A9A8A7
      AuthorizationType: NONE
      RouteKey: GET /health
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: HttpApiGEThealthCloudMapIntegrationF6876C3A
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/HttpApi/GET--health/Resource
  HttpApiANYquoteD542E79A:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: HttpApiF5A9A8A7
      AuthorizationType: NONE
      RouteKey: ANY /quote
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: HttpApiGEThealthCloudMapIntegrationF6876C3A
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/HttpApi/ANY--quote/Resource
  HttpApiANYquoteproxy4161C337:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: HttpApiF5A9A8A7
      AuthorizationType: NONE
      RouteKey: ANY /quote/{proxy+}
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: HttpApiGEThealthCloudMapIntegrationF6876C3A
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/HttpApi/ANY--quote--{proxy+}/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/2WQUWuDMBSFf0vzOGImUjboW9lDVyjbqLAXGSOLdyFVk5BcFQn+92HU0rKHkJzv3HsIJ2PZNmXphvc+EWWV1OqHhRy5qCjv/XcAkbGQg2idwuHgTGuLQDoryI48EEpK8MIpi8roSMYv+vKr7+b/gaOWDrwfKbdKcoSeD13GwqcVJ6WrIubOJ4YtnL4i2r1Vt/51Zm9V9HPkEoqVRhX52bQI98kTPmoE6fj0++vSDZtk3BxpbaRn4WTkWkG9PN94A0sXDhrT8frD1EoMZDd1g84M0UHQc0fPc0Nr0jhO6r1F2+JItSmBXfxjl23ZE0s3F69U4lqNqgF2nu8/gl0b+7EBAAA=
    Metadata:
      aws:cdk:path: EcsFargateNetworkingStack/CDKMetadata/Default
Outputs:
  ApiEndpoint:
    Value:
      Fn::GetAtt:
        - HttpApiF5A9A8A7
        - ApiEndpoint
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

